experiment:
  run_name_prefix: 'run_r50_rouge_1' # None für Datumscode als Experimentnamen
  users_dict: "data/restore" 
  number_of_users: 24 #None to process all
  number_of_rounds: 50 # How often the modell reflects on its results
  num_stimuli_to_process: 6 # Anzahl der Stimuli, die pro Iterration verarbeitet werden sollen, None für alle

  #async settings
  use async: true 
  num_workers: 6   # Number of user files to process in parallel.

evaluation:
  metrics:
    - rouge
    # - bertscore 
    # - perplexity
    # - bleu  
    # - llm_evaluation
    # - rouge

llm:
  persona_model: "google" # Modell für die Persona-Generierung
  imitation_model: "ollama" # Modell für die Imitations-Generierung
  reflection_model: "google_json" # Modell für die Reflexions-Generierung
  ollama_model: "gemma3:latest" # <-- HIER das Ollama-Modell festlegen

templates:
  persona_template: "persona_template_simple"
  imitation_post_template: "imitation_post_template_simple"
  imitation_reply_template: "imitation_replies_template_simple"
  reflection_template: "reflect_results_template"

